[package]
name = "oris"
version = "0.2.0"
edition = "2021"
description = "An interpreter for Monkey"
repository = "https://github.com/bebecue/oris"
license = "MIT"
categories = ["compilers"]

[[test]]
name = "tests"
harness = false
